#lang info
(define collection "umask")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/umask.scrbl" () (library))))
(define pkg-desc "Description Here")
(define version "0.1")
(define pkg-authors '("Winston Weinert"))
(define license '(MIT))
(define pkg-info "umask (file creation mask) utilities")
