on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' ${{ matrix.racket-variant }} ${{ matrix.os }}"
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        racket-version:
          - "stable"
          - "current"
        racket-variant:
          - "BC"
          - "CS"
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v0.12
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: install
        run: raco pkg install --auto --link umask-{doc,lib,test}
      - name: test
        run: raco test -e -p umask-{test,lib,doc}
